# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       xorg-x11-server
Summary:    X.Org X11 X server
Version:    1.10.6
Release:    1
Group:      System/X11
License:    MIT
URL:        http://cgit.freedesktop.org/xorg/xserver
Source0:    http://xorg.freedesktop.org/archive/individual/xserver/xorg-server-%{version}.tar.bz2
Source1:    00-input-default.conf
Source2:    10-input-synaptics.conf
Source3:    11-input-joystick.conf
Source100:  xorg-x11-server.yaml
Patch0:     xorg-x11-nonroot-vesa.patch
Patch1:     xorg-detect-psb.patch
Patch2:     use-sloppy-heuristic-first-for-initial-mode.patch
Patch3:     do-not-zap-xserver.patch
Patch4:     Lower-server-side-GLX-version.patch
Patch5:     reuse-buffer-notify.patch
Patch6:     Suppress-exposures-and-implicit-painting-for-some-re.patch
Requires:   libdrm >= 2.4.0
BuildRequires:  pkgconfig(xorg-macros)
BuildRequires:  pkgconfig(scrnsaverproto)
BuildRequires:  pkgconfig(xtrans)
BuildRequires:  pkgconfig(libdrm)
BuildRequires:  pkgconfig(randrproto)
BuildRequires:  pkgconfig(renderproto)
BuildRequires:  pkgconfig(kbproto)
BuildRequires:  pkgconfig(glproto)
BuildRequires:  pkgconfig(fixesproto)
BuildRequires:  pkgconfig(dri2proto)
BuildRequires:  pkgconfig(damageproto)
BuildRequires:  pkgconfig(xf86driproto)
BuildRequires:  pkgconfig(xcmiscproto)
BuildRequires:  pkgconfig(bigreqsproto)
BuildRequires:  pkgconfig(compositeproto)
BuildRequires:  pkgconfig(resourceproto)
BuildRequires:  pkgconfig(evieproto)
BuildRequires:  pkgconfig(xf86dgaproto)
BuildRequires:  pkgconfig(xf86vidmodeproto)
BuildRequires:  pkgconfig(recordproto)
BuildRequires:  pkgconfig(xkbfile)
BuildRequires:  pkgconfig(xres)
BuildRequires:  pkgconfig(xau)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xfont)
BuildRequires:  pkgconfig(fontenc)
BuildRequires:  pkgconfig(xdmcp)
BuildRequires:  pkgconfig(xt)
BuildRequires:  pkgconfig(dmx)
BuildRequires:  pkgconfig(xmuu)
BuildRequires:  pkgconfig(xrender)
BuildRequires:  pkgconfig(xi)
BuildRequires:  pkgconfig(xpm)
BuildRequires:  pkgconfig(xaw7)
BuildRequires:  pkgconfig(xfixes)
BuildRequires:  pkgconfig(xv)
BuildRequires:  pkgconfig(pixman-1)
BuildRequires:  pkgconfig(gl)
BuildRequires:  pkgconfig(dri)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(pciaccess)
BuildRequires:  pkgconfig(libudev)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(fontutil)
BuildRequires:  pkgconfig(xcomposite)
BuildRequires:  byacc
BuildRequires:  flex


%description
Description: %{summary}



%package devel
Summary:    SDK for X server driver module development
Group:      System/X11
Requires:   %{name} = %{version}-%{release}
Requires:   xorg-x11-util-macros
Requires:   pkgconfig
Requires:   pixman-devel
Requires:   libpciaccess-devel

%description devel
The SDK package provides the developmental files which are necessary for
developing X server driver modules, and for compiling driver modules
outside of the standard X11 source code tree.  Developers writing video
drivers, input drivers, or other X modules should install this package.


%package common
Summary:    Xorg server common files
Group:      System/X11
Requires:   %{name} = %{version}-%{release}

%description common
Common files shared among all X servers.

%package Xorg
Summary:    Xorg X server
Group:      System/X11
Requires:   %{name} = %{version}-%{release}
Requires:   xorg-x11-drv-mouse
Requires:   xorg-x11-drv-keyboard
Requires:   xorg-x11-drv-evdev
Requires:   xkbdata
Requires:   xkbcomp
Requires:   xorg-x11-server-common >= %{version}-%{release}
Conflicts:   %{name}-Xorg-setuid

%description Xorg
X.org X11 is an open source implementation of the X Window System.  It
provides the basic low level functionality which full fledged
graphical user interfaces (GUIs) such as GNOME and KDE are designed
upon.


%package Xorg-setuid
Summary:    Xorg X server with setuid
Group:      System/X11
Requires:   %{name} = %{version}-%{release}
Requires:   xorg-x11-drv-mouse
Requires:   xorg-x11-drv-keyboard
Requires:   xorg-x11-drv-evdev
Requires:   xkbdata
Requires:   xkbcomp
Requires:   xorg-x11-server-common >= %{version}-%{release}
Provides:   xorg-x11-server-Xorg = %{version}

%description Xorg-setuid
X.org X11 is an open source implementation of the X Window System.  It
provides the basic low level functionality which full fledged
graphical user interfaces (GUIs) such as GNOME and KDE are designed
upon.


%package Xephyr
Summary:    A nested X server.
Group:      System/X11
Requires:   %{name} = %{version}-%{release}

%description Xephyr
Xephyr is an X server, which has been implemented as an ordinary
X application.  It runs in a window just like other X applications,
but it is an X server itself in which you can run other software.  It
is a very useful tool for developers who wish to test their
applications without running them on their real X server.  Unlike
Xnest, Xephyr renders to an X image rather than relaying the
X protocol, and therefore supports the newer X extensions like
Render and Composite.



%prep
%setup -q -n xorg-server-%{version}

# xorg-x11-nonroot-vesa.patch
%patch0 -p1
# xorg-detect-psb.patch
%patch1 -p1
# use-sloppy-heuristic-first-for-initial-mode.patch
%patch2 -p1
# do-not-zap-xserver.patch
%patch3 -p1
# Lower-server-side-GLX-version.patch
%patch4 -p1
# reuse-buffer-notify.patch
%patch5 -p1
# Suppress-exposures-and-implicit-painting-for-some-re.patch
%patch6 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --enable-maintainer-mode \
    --enable-config-udev \
    --disable-config-hal \
    --disable-xvfb \
    --disable-xnest \
    --disable-dmx \
    --enable-kdrive \
    --enable-xephyr \
    --disable-xfake \
    --disable-xfbdev \
    --enable-xorg \
    --with-pic \
    --with-default-font-path="catalogue:/etc/X11/fontpath.d,built-ins" \
    --with-module-dir=%{_libdir}/xorg/modules \
    --with-builderstring="Build ID: %{name} %{version}-%{release}" \
    --with-xkb-output=%{_localstatedir}/cache/xkb \
    --disable-xselinux \
    --disable-xinerama \
    --enable-dri2 \
    --enable-dri \
    --with-dri-driver-path=%{_libdir}/dri

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install
mkdir -p %{buildroot}/etc/X11/xorg.conf.d
cp -a %{SOURCE1} %{buildroot}/etc/X11/xorg.conf.d
mkdir -p %{buildroot}/etc/X11/xorg.conf.d
cp -a %{SOURCE2} %{buildroot}/etc/X11/xorg.conf.d
mkdir -p %{buildroot}/etc/X11/xorg.conf.d
cp -a %{SOURCE3} %{buildroot}/etc/X11/xorg.conf.d


# >> install post
# << install post





















%files
%defattr(-,root,root,-)
# >> files
# this section/file is intentionally left blank
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/pkgconfig/xorg-server.pc
%dir %{_includedir}/xorg
%{_includedir}/xorg/*.h
%{_datadir}/aclocal/xorg-server.m4
%{_datadir}/X11/xorg.conf.d/10-evdev.conf
# << files devel

%files common
%defattr(-,root,root,-)
# >> files common
%doc %{_mandir}/man1/Xserver.1*
%{_libdir}/xorg/protocol.txt
# dir for caching xkb comp results, must be writable by non-root users
%dir %attr(777,-,-) %{_localstatedir}/cache/xkb
%attr(644,-,-) %{_localstatedir}/cache/xkb/README.compiled
# << files common

%files Xorg
%defattr(-,root,root,-)
# >> files Xorg
%{_bindir}/X
%{_bindir}/Xorg
%{_bindir}/gtf
%{_bindir}/cvt
%config(noreplace) /etc/X11/xorg.conf.d/00-input-default.conf
%config(noreplace) /etc/X11/xorg.conf.d/10-input-synaptics.conf
%config(noreplace) /etc/X11/xorg.conf.d/11-input-joystick.conf
%dir %{_libdir}/xorg
%dir %{_libdir}/xorg/modules
%dir %{_libdir}/xorg/modules/extensions
%{_libdir}/xorg/modules/extensions/libglx.so
%{_libdir}/xorg/modules/extensions/libdri.so
%{_libdir}/xorg/modules/extensions/libdri2.so
%{_libdir}/xorg/modules/extensions/libdbe.so
%{_libdir}/xorg/modules/extensions/libextmod.so
%{_libdir}/xorg/modules/extensions/librecord.so
%dir %{_libdir}/xorg/modules/multimedia
%{_libdir}/xorg/modules/multimedia/bt829_drv.so
%{_libdir}/xorg/modules/multimedia/fi1236_drv.so
%{_libdir}/xorg/modules/multimedia/msp3430_drv.so
%{_libdir}/xorg/modules/multimedia/tda8425_drv.so
%{_libdir}/xorg/modules/multimedia/tda9850_drv.so
%{_libdir}/xorg/modules/multimedia/tda9885_drv.so
%{_libdir}/xorg/modules/multimedia/uda1380_drv.so
%{_libdir}/xorg/modules/libexa.so
%{_libdir}/xorg/modules/libfb.so
%{_libdir}/xorg/modules/libint10.so
%{_libdir}/xorg/modules/libshadow.so
%{_libdir}/xorg/modules/libshadowfb.so
%{_libdir}/xorg/modules/libvbe.so
%{_libdir}/xorg/modules/libvgahw.so
%{_libdir}/xorg/modules/libfbdevhw.so
%{_libdir}/xorg/modules/libwfb.so
%{_libdir}/xorg/modules/libxaa.so
%doc %{_mandir}/man1/gtf.1*
%doc %{_mandir}/man1/Xorg.1*
%doc %{_mandir}/man1/cvt.1*
%doc %{_mandir}/man4/fbdevhw.4*
%doc %{_mandir}/man4/exa.4*
%doc %{_mandir}/man5/xorg.conf.5*
%doc %{_mandir}/man5/xorg.conf.d.5*
# << files Xorg

%files Xorg-setuid
%defattr(-,root,root,-)
# >> files Xorg-setuid
%{_bindir}/X
%attr(4711, root, root) %{_bindir}/Xorg
%{_bindir}/gtf
%{_bindir}/cvt
%config(noreplace) /etc/X11/xorg.conf.d/00-input-default.conf
%config(noreplace) /etc/X11/xorg.conf.d/10-input-synaptics.conf
%config(noreplace) /etc/X11/xorg.conf.d/11-input-joystick.conf
%dir %{_libdir}/xorg
%dir %{_libdir}/xorg/modules
%dir %{_libdir}/xorg/modules/extensions
%{_libdir}/xorg/modules/extensions/libglx.so
%{_libdir}/xorg/modules/extensions/libdri.so
%{_libdir}/xorg/modules/extensions/libdri2.so
%{_libdir}/xorg/modules/extensions/libdbe.so
%{_libdir}/xorg/modules/extensions/libextmod.so
%{_libdir}/xorg/modules/extensions/librecord.so
%dir %{_libdir}/xorg/modules/multimedia
%{_libdir}/xorg/modules/multimedia/bt829_drv.so
%{_libdir}/xorg/modules/multimedia/fi1236_drv.so
%{_libdir}/xorg/modules/multimedia/msp3430_drv.so
%{_libdir}/xorg/modules/multimedia/tda8425_drv.so
%{_libdir}/xorg/modules/multimedia/tda9850_drv.so
%{_libdir}/xorg/modules/multimedia/tda9885_drv.so
%{_libdir}/xorg/modules/multimedia/uda1380_drv.so
%{_libdir}/xorg/modules/libexa.so
%{_libdir}/xorg/modules/libfb.so
%{_libdir}/xorg/modules/libint10.so
%{_libdir}/xorg/modules/libshadow.so
%{_libdir}/xorg/modules/libshadowfb.so
%{_libdir}/xorg/modules/libxaa.so
%{_libdir}/xorg/modules/libvbe.so
%{_libdir}/xorg/modules/libvgahw.so
%{_libdir}/xorg/modules/libfbdevhw.so
%{_libdir}/xorg/modules/libwfb.so
%doc %{_mandir}/man1/gtf.1*
%doc %{_mandir}/man1/Xorg.1*
%doc %{_mandir}/man1/cvt.1*
%doc %{_mandir}/man4/fbdevhw.4*
%doc %{_mandir}/man4/exa.4*
%doc %{_mandir}/man5/xorg.conf.5*
%doc %{_mandir}/man5/xorg.conf.d.5*
# << files Xorg-setuid

%files Xephyr
%defattr(-,root,root,-)
# >> files Xephyr
%{_bindir}/Xephyr
%doc %{_mandir}/man1/Xephyr.1*
# << files Xephyr

